### ISSUE TITLE
Spline specification not working

### ISSUE THREAD

**Issue by BenKearns** [chjackson/survextrap#7]
When attempting to replicate the cetuximab case-study, an error arises with the code:
mspline <- mspline_spec(Surv(years, d) ~ 1, data=cetux, df=6, add_knots=20)
(from https://chjackson.github.io/survextrap/articles/cetuximab.html)

Error output is:
Error in make_td(mf) : argument "data" is missing, with no default

This error also occurs when using other datasets.

**Comment by chjackson** [comment]
Thanks - I think this is now fixed in https://github.com/chjackson/survextrap/commit/ec2ecd9a7839f7f40de006ac9e9f0104b27ca14e and the r-universe version has updated with the fix.
